version: '3.8'

services:
  frontend:
    image: commodity/frontend
    container_name: frontend
    build: 
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_URL: http://localhost:8888/api
    depends_on:
      - backend
    networks:
      - commodity
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commodities
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - commodity

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - commodity

  backend:
    image: commodity/csharp
    container_name: backend
    build:
      context: .
      dockerfile: dotnet.Dockerfile
    depends_on:
      - mysql
    networks:
      - commodity
    ports:
      - "8888:8080"
    environment:
      MySql__ConnectionString: "server=mysql;database=commodities;user=user;password=password"
      Soap__Endpoint: "http://soap:8080/Commodity"
    entrypoint: [ "sh", "-c", "sleep 10 && dotnet Commodity.API.dll" ]

  soap:
    image: commodity/soap
    container_name: soap
    build:
      context: .
      dockerfile: java.Dockerfile
    networks:
      - commodity

networks:
  commodity:

volumes:
  mysql_data: